import React from 'react'

export const metadata = {
  
    title: 'CountryPay - Dashboard',
    description: 'Generated by create next app',
    
  }
  

function LayoutDashoard({children}) {
  return (
    <div>
        {children}
    </div>
  )
}

export default LayoutDashoard