import { FooterComp } from './Components/Footer'
import { NavBar } from './Components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  
  title: 'CountryPay',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
  
      </head>

      <body className={inter.className}>
        <NavBar/>
      
      <main className='h-full' >  
      {children}
      
      </main>
      
      <FooterComp/>
      
      </body>
    </html>
  )
}
